// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB6yKAuMtNGAbPGXj-BcaUW1MQfrVvKAE',
    appId: '1:244758209328:web:310dbd37c0303fe3329ef5',
    messagingSenderId: '244758209328',
    projectId: 'notes-d6089',
    authDomain: 'notes-d6089.firebaseapp.com',
    storageBucket: 'notes-d6089.appspot.com',
    measurementId: 'G-Y7GTS6WKZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa8Umg4KO6dvLN_E4FFzAjtSuSMEyyUSQ',
    appId: '1:244758209328:android:241fd840f192c4d7329ef5',
    messagingSenderId: '244758209328',
    projectId: 'notes-d6089',
    storageBucket: 'notes-d6089.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwDvlkdzjb8bFMGDhIz1aNUafQlAey74g',
    appId: '1:244758209328:ios:ff4a7ad38123f529329ef5',
    messagingSenderId: '244758209328',
    projectId: 'notes-d6089',
    storageBucket: 'notes-d6089.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwDvlkdzjb8bFMGDhIz1aNUafQlAey74g',
    appId: '1:244758209328:ios:001c5a50182d12dd329ef5',
    messagingSenderId: '244758209328',
    projectId: 'notes-d6089',
    storageBucket: 'notes-d6089.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
