// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALn-2tfFtP_THIIDInlgr2XNOm0jwjkbg',
    appId: '1:228568473510:web:e749b3308ba691b47df967',
    messagingSenderId: '228568473510',
    projectId: 'notes-26d8d',
    authDomain: 'notes-26d8d.firebaseapp.com',
    storageBucket: 'notes-26d8d.appspot.com',
    measurementId: 'G-1RNBEHDGEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkQIci8RQT1FmthQ2WZ2UwJykInCQSjos',
    appId: '1:228568473510:android:260d71f9b5e55f4a7df967',
    messagingSenderId: '228568473510',
    projectId: 'notes-26d8d',
    storageBucket: 'notes-26d8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6WHJL4X_mxna0uGNJtvl5sS7QyZT-nbs',
    appId: '1:228568473510:ios:4a2aea6a5bd4f14d7df967',
    messagingSenderId: '228568473510',
    projectId: 'notes-26d8d',
    storageBucket: 'notes-26d8d.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6WHJL4X_mxna0uGNJtvl5sS7QyZT-nbs',
    appId: '1:228568473510:ios:4a2aea6a5bd4f14d7df967',
    messagingSenderId: '228568473510',
    projectId: 'notes-26d8d',
    storageBucket: 'notes-26d8d.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALn-2tfFtP_THIIDInlgr2XNOm0jwjkbg',
    appId: '1:228568473510:web:81de05828c60e46e7df967',
    messagingSenderId: '228568473510',
    projectId: 'notes-26d8d',
    authDomain: 'notes-26d8d.firebaseapp.com',
    storageBucket: 'notes-26d8d.appspot.com',
    measurementId: 'G-6Q3LG3X3BT',
  );

}